server:
  port: 6666
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: zkf-wx-chatbot
# 配置文件环境
  profiles:
    active: prod

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8

# Redis
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 100000


# 高德地图api地址
Gould_Url: https://restapi.amap.com/v3/weather/weatherInfo
# 高德地图key
Gould_Key: 096a28e87615d639bfe6310cbc98e224
